// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm8Eek3gxHYwIo2GAa-J0Ayin7X78NRow',
    appId: '1:448873934281:web:9bf1c253b0c178c0f7cc18',
    messagingSenderId: '448873934281',
    projectId: 'tasty-project-2',
    authDomain: 'tasty-project-2.firebaseapp.com',
    storageBucket: 'tasty-project-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqx-zsO8Ad9gSeztY42olUp8k6PTS6IMc',
    appId: '1:448873934281:android:e1b9b118593d0be8f7cc18',
    messagingSenderId: '448873934281',
    projectId: 'tasty-project-2',
    storageBucket: 'tasty-project-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaugJz2WwCEUB6TiE3kKJ6TzQM_EhhFVc',
    appId: '1:448873934281:ios:6ae4154c01f114d6f7cc18',
    messagingSenderId: '448873934281',
    projectId: 'tasty-project-2',
    storageBucket: 'tasty-project-2.firebasestorage.app',
    iosBundleId: 'com.example.tastyRestaurant2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaugJz2WwCEUB6TiE3kKJ6TzQM_EhhFVc',
    appId: '1:448873934281:ios:6ae4154c01f114d6f7cc18',
    messagingSenderId: '448873934281',
    projectId: 'tasty-project-2',
    storageBucket: 'tasty-project-2.firebasestorage.app',
    iosBundleId: 'com.example.tastyRestaurant2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm8Eek3gxHYwIo2GAa-J0Ayin7X78NRow',
    appId: '1:448873934281:web:8b6842d52aa33377f7cc18',
    messagingSenderId: '448873934281',
    projectId: 'tasty-project-2',
    authDomain: 'tasty-project-2.firebaseapp.com',
    storageBucket: 'tasty-project-2.firebasestorage.app',
  );
}
